version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: purchasesContainer
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: purchases

    ports:
      - 1234:3306
    cap_add:
      - SYS_NICE
